### ISSUE TITLE
Error when running .jar file 

### ISSUE THREAD

**Issue by MKolman** [Sheep-y/trpg-dnd-4e-db#26]
## Steps to reproduce the error
Download `4e_compendium_downloader.jar` and run it using
`java -jar 4e_compendium_downloader.jar`
## Expected result
Application starts
## Actual result
```
$ java -jar 4e_compendium_downloader.jar 
Error: Could not find or load main class db4e.Main
```
## System information
OS: Arch Linux
```
$ uname -a
Linux ra 4.8.4-1-ARCH #1 SMP PREEMPT Sat Oct 22 18:26:57 CEST 2016 x86_64 GNU/Linux
```
Java version: java-8-openjdk
```
$ java -version
openjdk version "1.8.0_112"
OpenJDK Runtime Environment (build 1.8.0_112-b15)
OpenJDK 64-Bit Server VM (build 25.112-b15, mixed mode)
```

**Comment by Sheep-y** [comment]
Can reproduce with OpenJDK on windows, will try to see what's wrong.  Thanks for raising the issue.

**Comment by Sheep-y** [comment]
Turns out it has nothing to do with the jar or the class in it.

OpenJDK doesn't come with OpenJFX by default, which the main class depends on.
If you build OpenJFX + Webkit and put them into OpenJDK, the jar should loads and run.

I'll add a detection to provide more meaningful message in next release.
