### ISSUE TITLE
Downloaded compendium, now what?

### ISSUE THREAD

**Issue by bombshellbonny** [Sheep-y/trpg-dnd-4e-db#31]
Sorry for the confusion on my part, but I've run the downloader and have downloaded the database information, but I don't understand what I'm suppose to do next?  I've downloaded trpg-dnd-4e-db, but all I see are xml files that I can't excute.  I also have CocoDoc, but it also only has xml files that I can't run.  I'm a complete noob when it comes to this stuff, so any more information you could give me would be greatly appreciated.

Also, is it possible to export as a CSV file?  I've tried to download SQLJet to test a conversion process, but the download keeps freezing.

**Comment by bombshellbonny** [comment]
Just an update, I was able to dump the .database file to a sql file via sqlite, so I've got that going for me.

**Comment by Sheep-y** [comment]
Hmm. Sorry, I am not sure where you are at.
Can you launch the program and see a message that says "Ready to Download" or "Ready to Export"?

Yes I can add the ability to export as CSV in next version.
I guess I'll throw in an Excel export too, before someone open an issue for that.

I expect next version to be ready in about a week, after which I'll try to record a YouTube video to demo it.

**Comment by Sheep-y** [comment]
Ok, the export part is easy.  Using it may be less easy.

I don't know what you want to do with the data but be warning that the csv may not be suitable for Excel, mainly because Excel's cell text is limited to [32k characters](https://support.office.com/en-gb/article/Excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3) max, which some classes and paragon paths exceeds.

So what I do with the xlsx export is I split the content into second, third, or even fourth cell.
(And no, merged cell would not increase the limit.)

Google Sheet doesn't like any of the exports (csv/tsv/xlsx). Way worse than Excel.
Since Google does not provide any hint (another worse), there is not much I can do.

Excel is a spreadsheet, after all, not a proper database.  Maybe I should add SQL export too.

**Comment by Sheep-y** [comment]
Ok, there is a new release ([v3.5.3](https://github.com/Sheep-y/trpg-dnd-4e-db/releases/tag/release%2F3.5.3)) with xlsx/csv/sql export and a [new video](https://youtu.be/aNDze9Ok5fE) that demos how the program is intended to be used.

Let me know if you still have questions.  For now I'll file this issue as case closed.
