### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by frumello** [Sheep-y/trpg-dnd-4e-db#33]
The program in the browser is written all in Chinese, how do i change to english?

**Comment by frumello** [comment]
Forget i just found in the about

**Comment by Sheep-y** [comment]
The current release has a bug where after you selected a language, resetting it to auto detect would not take effect until next launch (will be fixed next release).  Otherwise, the language detection should respect your browser's language preference, using English as default unless you have Chinese (any) on the list _and_ has a higher priority than English.  This usually happens when you use a Chinese browser or if you are running a Chinese system.

If this is not your case, this may be a bug and it would be nice to know more details.

**Comment by frumello** [comment]
I did a fresh install in my Notebook and when i opened the browser It was
in chinese.
My language option is pt-br (brasilian portuguese), windows 10 pro, chrome.
By the way great software, its sad that wotc did the 5th for me is so
unbalanced and simple.

Em 19/03/2017 08:38, "Sheep-y" <notifications@github.com> escreveu:

**Comment by Sheep-y** [comment]
Thanks for the info.  I can't reproduce the issue, but I think I'll go ahead and default to English in future version anyway.  Anyone who use the compendium has to be reasonably fluent in English, so it's the safe bet.
